version: "3"
services:
  backend:
    build:
      context: "./backend"
      dockerfile: "Dockerfile.dev"
    command: npm run start:debug
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
  frontend:
    build:
      context: "./frontend"
      dockerfile: "Dockerfile.dev"
    command: npm run start
    volumes:
      - ./frontend:/app
    ports:
      - "4000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
  db:
    platform: linux/x86_64
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: "onboard"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "secret"
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_ROOT_HOST: "0.0.0.0"
    ports:
      - "3306:3306"
